version: '3.4'

x-vars:
  volumes:
    frontend: &volumes-frontend
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/node_modules:/app/node_modules
    backend: &volumes-backend
      - ./backend/api:/api/api
      - ./backend/app:/api/app
      - ./backend/config:/api/config
      - ./backend/scrapers:/api/scrapers
      - ./backend/tests:/api/tests
      - ./backend/utils:/api/utils
      - ./backend/vendors:/api/vendors
      - ./backend/scrape.py:/api/scrape.py
  env-files:
    frontend: &env-files-frontend
      - ./frontend/.env.development.local
    backend: &env-files-backend
      - ./backend/config/.env

services:
  db:
    image: postgres:latest
    volumes:
      - ./config/kbpartpicker.sql:/docker-entrypoint-initdb.d/10-init.sql
    environment:
      - POSTGRES_USER=kbpp
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=kbpartpicker
    ports:
      - 5432:5432
    restart: always
    
  web:
    build:
      context: frontend
      dockerfile: Dockerfile
    user: kbpp
    volumes: *volumes-frontend
    env_file: *env-files-frontend
    ports:
      - 3000:3000
    stdin_open: true

  api:
    build: ./backend
    depends_on:
      - db
    user: kbpp
    volumes: *volumes-backend
    env_file: *env-files-backend
    ports:
      - 5000:5000
    command: >
      bash -c "python scrape.py
      & gunicorn --reload -b 0.0.0.0:5000 run:app"
